name: Build Artifacts with custom patches
run-name: "PG ${{ inputs.postgres_version }}. Custom PG ${{ inputs.custom_postgres_version }}"
on:
  workflow_dispatch:
    inputs:
      postgres_version:
        description: "PostgreSQL version to build (15, 16, 17)"
        type: choice
        options:
          - "15"
          - "16"
          - "17"
        default: "17"
        required: false
      custom_postgres_version:
        description: "Custom PostgreSQL version label (e.g. 17.3-1)"
        type: string
        default: "17.6-2"
        required: false
      publish_docker:
        description: "Publish image to ghcr.io/github.repository_owner/pgskipper-patroni"
        type: boolean
        default: true
        required: false

env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  PUSH: ${{ (github.event_name != 'workflow_dispatch' || inputs.publish_docker) && github.actor != 'dependabot[bot]' }}

jobs:
  multiplatform_build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        targetarch:
          - arm64
          - amd64

    runs-on: ubuntu-24.04
    steps:
      - name: Validate
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" == refs/tags* ]]; then
            echo -e "\033[91mManual workflow run on tags is not allowed!\033[0m"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          no-cache: true
          context: '.'
          file: Dockerfile-multi-custom
          build-args: |
            PG_VERSION=${{ inputs.postgres_version }}
            CUSTOM_PG_VERSION=${{ inputs.custom_postgres_version }}
            TARGETARCH=${{ matrix.targetarch }}
          platforms: linux/${{ matrix.targetarch }}
          push: ${{ env.PUSH }}
          tags: ghcr.io/${{ github.repository_owner }}/pgskipper-patroni-${{ inputs.postgres_version}}:custom-patches-${{ inputs.custom_postgres_version }}
          provenance: false
